apiVersion: v1
kind: Service
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-service
  namespace: scratch
spec:
  ports:
  - port: 5672
  selector:
    app: taskQueue
    component: rabbitmq

---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: rabbitmq
  name: aiida-rabbitmq-controller
  namespace: scratch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: taskQueue
        component: rabbitmq
    spec:
      containers:
      - image: rabbitmq
        name: rabbitmq
        ports:
        - containerPort: 5672
        resources:
          limits:
            cpu: 100m
