ingress:
  host: "local-chart.example.com"
resources:
  requests:
    cpu: 100m
    memory: 512M
    gpu: 0
  limits:
    cpu: 300m
    memory: 1G
    gpu: 0
persistentStorage:
  - existingClaim: ""
    existingClaimName: "example-name"
    subPath: "/"
appstore_generated_data:
  appstore_meta_data:
    contact_email: "example@uninett.no"
  dataporten:
    scopes:
      - ""
    id: "0000-abc"
    owner: "0000-1234"
    client_secret: "0000-0000"
    authorized_groups:
      - ""
uid: 999
gid: 999
username: vncuser
supplementalGroups:
  - name: ""
    gid: ""
authGroupProviders:
  - url: "https://groups-api.dataporten.no/groups/me/groups"
    scope: groups
advanced:
  dockerImage: quay.io/uninett/desktop-vnc:20200302-7386b14
