auth:
  type: "dataporten"
persistentStorage:
  - existingClaim: ""
    existingClaimName: "example-name"
    subPath: "/"
ingress:
  host: "test.localhost"
userNotebookType:
  resources:
    requests:
      cpu: "1"
      memory: 1G
      gpu: 0
    limits:
      cpu: "2"
      memory: 1G
      gpu: 0
users:
  resources:
    options:
      - id: "< 200"
        requests:
            cpu: "0.5"
            memory: 512M
        limits:
            cpu: "1"
            memory: 1G
      - id: "200-500"
        requests:
            cpu: "1"
            memory: 1G
        limits:
            cpu: "2"
            memory: 1G
      - id: "> 500"
        requests:
            cpu: "1"
            memory: 2G
        limits:
            cpu: "2"
            memory: 2G
    selected:
      requests:
        cpu: "0.5"
        memory: 512M
      limits:
        cpu: "1"
        memory: 1G
uid: 999
gid: 999
username: hub
supplementalGroups:
  - name: ""
    gid: ""
advanced:
  dbUrl: "sqlite://"
  debug: false
  jupyterLab: true
  userHomeAddStorageSubPath: true
  userHomeSubPath: "dataporten-home"
  startTimeout: 300
  notebook:
    spawnLimit: 100
  additionalAdmin:
    - ""
  killIdlePods:
    enabled: true
    timeout: 3600
    concurrency: 10
  ipyparallel:
    enabled: false
    workers: 2
    image: "quay.io/ntnu/jh_su_default:20210105"
    resources:
      requests:
        cpu: "1"
        memory: 1G
        gpu: 0
      limits:
        cpu: "2"
        memory: 1G
        gpu: 0
  vnc:
    enabled: false
    image: "quay.io/uninett/desktop-vnc:20200518-9fef810"
    resources:
      requests:
        cpu: "1"
        memory: 1G
      limits:
        cpu: "2"
        memory: 1G
  nbgrader:
    enabled: false
    teacher: false
    token: ""
    ngshareurl: ""
    ngsharesvc: ""
  sharedData:
    enabled: false
    subPath: "data"
    readOnly: true
  minio:
    enabled: false
    minioAccessKey: "accesskeyexample"
    minioSecretKey: "secretkeyexample"
  userImage: quay.io/ntnu/jh_su_default:20210105
  userAltImage: quay.io/ntnu/jh_su_default:20210105
  hubImage: quay.io/ntnu/jh_srv:20201218
  imagePullPolicy: "IfNotPresent"
  privatereg: 
    enabled: false
    secret: ""
appstore_generated_data:
  appstore_meta_data:
    contact_email: "example@uninett.no"
  dataporten:
    id: ""
    owner: "0000-1234"
    client_secret: ""
    authorized_groups:
      - ""
authGroupProviders:
  - url: "https://groups-api.dataporten.no/groups/me/groups"
    scope: groups
userInfoURL: "https://auth.dataporten.no/openid/userinfo"
ingressControllerNamespaceLabel: ingress-nginx
