apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-proxy-api
  annotations:
    appstore.uninett.no/contact_email: {{ .Values.appstore_generated_data.appstore_meta_data.contact_email }}
  labels:
    group: {{ .Release.Name }}-jupyterhub
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    name: {{ .Release.Name }}-proxy
    component: proxy
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-proxy-http
  annotations:
    appstore.uninett.no/contact_email: {{ .Values.appstore_generated_data.appstore_meta_data.contact_email }}
  labels:
    group: {{ .Release.Name }}-jupyterhub
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  selector:
    name: {{ .Release.Name }}-proxy
    component: proxy
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
