ingress:
  host: "local-chart.example.com"
resources:
  requests:
    cpu: 1
    memory: 1G
    gpu: 0
  limits:
    cpu: 2
    memory: 1G
    gpu: 0
persistentStorage:
  - existingClaim: ""
    existingClaimName: "example-name"
    subPath: "/"
appstore_generated_data:
  appstore_meta_data:
    contact_email: "example@uninett.no"
  dataporten:
    scopes:
      - ""
    id: "0000-abc"
    owner: "0000-1234"
    client_secret: "0000-0000"
    authorized_groups:
      - ""
uid: 999
gid: 999
username: notebook
supplementalGroups:
  - name: ""
    gid: ""
advanced:
  env:
    sparkMasterUrl: "local[*]"
    jupyterLab: false
  dockerImage: quay.io/uninett/jupyter-spark:20200420-1131dd2
  githubToken: ""
authGroupProviders:
  - url: "https://groups-api.dataporten.no/groups/me/groups"
    scope: groups
